//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_And_Doors_Project_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Details
    {
        public int Employee_Id { get; set; }
        public string Name { get; set; }
        public decimal Mobile_No { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Adhaar_No { get; set; }
        public string Account_No { get; set; }
        public string Qualification { get; set; }
        public string Experience { get; set; }
        public System.DateTime Joining_Date { get; set; }
    
        public virtual Employee_salary Employee_salary { get; set; }
    }
}
