//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_And_Doors_Project_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Customer_Transaction = new HashSet<Customer_Transaction>();
            this.Distributor_Transaction = new HashSet<Distributor_Transaction>();
            this.Ordered_Items = new HashSet<Ordered_Items>();
        }
    
        public int Order_Id { get; set; }
        public int Customer_Id { get; set; }
        public int User_Id { get; set; }
        public System.DateTime Order_Date { get; set; }
        public decimal Installation_Charge { get; set; }
        public double GST { get; set; }
        public double Discount { get; set; }
        public decimal Total { get; set; }
        public decimal Paid_Amount { get; set; }
        public decimal Remaining_Amount { get; set; }
        public System.DateTime Delivery_Date { get; set; }
        public string Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Transaction> Customer_Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Distributor_Transaction> Distributor_Transaction { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordered_Items> Ordered_Items { get; set; }
    }
}
