//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_And_Doors_Project_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Order_Items
    {
        public int Stock_Order_Items_Id { get; set; }
        public string Material_Name { get; set; }
        public string Type { get; set; }
        public string Colour { get; set; }
        public Nullable<int> Track { get; set; }
        public Nullable<int> Size { get; set; }
        public int Quantity { get; set; }
        public decimal Purchase_Price { get; set; }
        public int Order_Stock_Id { get; set; }
    
        public virtual Stock_Order Stock_Order { get; set; }
    }
}
