//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_And_Doors_Project_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock_Order()
        {
            this.Stock_Order_Items = new HashSet<Stock_Order_Items>();
        }
    
        public int Order_Stock_Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Distributor_Name { get; set; }
        public decimal Total { get; set; }
        public decimal Paid_Amount { get; set; }
        public decimal Remaining_Amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_Order_Items> Stock_Order_Items { get; set; }
    }
}
